"""empty message

Revision ID: 052e5edbdf5d
Revises: 9ad747adbff1
Create Date: 2017-01-26 16:42:43.829000

"""

# revision identifiers, used by Alembic.
revision = '052e5edbdf5d'
down_revision = '9ad747adbff1'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_EveApiScope_scopeName', table_name='EveApiScope')
    op.add_column('accounts', sa.Column('had_welcome_mail', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    op.create_index(op.f('ix_eveapiscope_scopeName'), 'EveApiScope', ['scopeName'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ##
    op.drop_index(op.f('ix_eveapiscope_scopeName'), table_name='EveApiScope')
    op.create_index('ix_EveApiScope_scopeName', 'EveApiScope', ['scopeName'], unique=False)
    op.drop_column('accounts', 'had_welcome_mail')

    ### end Alembic commands ###
