"""empty message

Revision ID: 09414b495bb5
Revises: 8f6e88746b77
Create Date: 2017-01-24 22:10:55.779000

"""

# revision identifiers, used by Alembic.
revision = '09414b495bb5'
down_revision = '8f6e88746b77'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_history', sa.Column('restriction_level', sa.SmallInteger(), server_default=sa.text(u'50'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_history', 'restriction_level')
    ### end Alembic commands ###
