"""empty message

Revision ID: 1877262ba3de
Revises: 839456a7e73e
Create Date: 2016-03-07 12:06:57.784000

"""

# revision identifiers, used by Alembic.
revision = '1877262ba3de'
down_revision = '839456a7e73e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fittings', sa.Column('wl_type', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fittings', 'wl_type')
    ### end Alembic commands ###
