"""empty message

Revision ID: 1df18eabcc13
Revises: f363cde2b713
Create Date: 2019-05-24 20:52:06.867464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df18eabcc13'
down_revision = 'f363cde2b713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('murmur_dati',
    sa.Column('murmur_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('grpc_host', sa.String(length=128), nullable=True),
    sa.Column('grpc_port', sa.Integer(), nullable=True),
    sa.Column('display_host', sa.String(length=128), nullable=True),
    sa.Column('display_port', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('safety_channel_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('murmur_id', name=op.f('pk_murmur_dati'))
    )
    op.create_table('mumble_user',
    sa.Column('murmur_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_mumble_user_account_id_accounts'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('murmur_id', name=op.f('pk_mumble_user')),
    sa.UniqueConstraint('account_id', name=op.f('uq_mumble_user_account_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mumble_user')
    op.drop_table('murmur_dati')
    # ### end Alembic commands ###
