"""empty message

Revision ID: 23a7fc516054
Revises: 687970b3617d
Create Date: 2017-02-11 16:25:07.952780

"""

# revision identifiers, used by Alembic.
revision = '23a7fc516054'
down_revision = '687970b3617d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_event_ibfk_2', 'calendar_event', type_='foreignkey')
    op.create_foreign_key(None, 'calendar_event', 'calendar_category', ['eventCategoryID'], ['categoryID'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.create_foreign_key('calendar_event_ibfk_2', 'calendar_event', 'calendar_category', ['eventCategoryID'], ['categoryID'], onupdate='CASCADE')
    # ### end Alembic commands ###
