"""empty message

Revision ID: 3f55d9c10c62
Revises: 67b88f2530bb
Create Date: 2017-03-29 14:21:21.005320

"""

# revision identifiers, used by Alembic.
revision = '3f55d9c10c62'
down_revision = '67b88f2530bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permission_roles',
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
