"""empty message

Revision ID: 44045584e815
Revises: 44a477268e5e
Create Date: 2016-03-08 19:46:54.564000

"""

# revision identifiers, used by Alembic.
revision = '44045584e815'
down_revision = '44a477268e5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solarsystem',
    sa.Column('solarSystemID', sa.Integer(), nullable=False),
    sa.Column('solarSystemName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('solarSystemID')
    )
    op.create_index(op.f('ix_solarsystem_solarSystemName'), 'solarsystem', ['solarSystemName'], unique=True)
    op.create_table('station',
    sa.Column('stationID', sa.Integer(), nullable=False),
    sa.Column('stationName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('stationID')
    )
    op.create_index(op.f('ix_station_stationName'), 'station', ['stationName'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_stationName'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_solarsystem_solarSystemName'), table_name='solarsystem')
    op.drop_table('solarsystem')
    ### end Alembic commands ###
