"""empty message

Revision ID: 463d72677b83
Revises: 966332ddb8ba
Create Date: 2016-04-18 22:53:50.477000

"""

# revision identifiers, used by Alembic.
revision = '463d72677b83'
down_revision = '966332ddb8ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_groups', sa.Column('influence', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_groups', 'influence')
    ### end Alembic commands ###
