"""empty message

Revision ID: 4f84a51ec263
Revises: d40cb6e101dc
Create Date: 2016-04-07 18:36:22.701000

"""

# revision identifiers, used by Alembic.
revision = '4f84a51ec263'
down_revision = 'd40cb6e101dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_history',
    sa.Column('historyID', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('sourceID', sa.Integer(), nullable=True),
    sa.Column('targetID', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['sourceID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['targetID'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('historyID')
    )
    op.create_table('comp_history_fits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historyID', sa.Integer(), nullable=True),
    sa.Column('fitID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitID'], ['fittings.id'], ),
    sa.ForeignKeyConstraint(['historyID'], ['comp_history.historyID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comp_history_fits')
    op.drop_table('comp_history')
    ### end Alembic commands ###
