"""empty message

Revision ID: 59521a50becc
Revises: f549a192f3e5
Create Date: 2016-04-12 19:41:05.201000

"""

# revision identifiers, used by Alembic.
revision = '59521a50becc'
down_revision = 'f549a192f3e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comp_history_ext_inv', sa.Column('historyID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comp_history_ext_inv', 'comp_history', ['historyID'], ['historyID'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comp_history_ext_inv', type_='foreignkey')
    op.drop_column('comp_history_ext_inv', 'historyID')
    ### end Alembic commands ###
