"""empty message

Revision ID: 5d4117fe39fe
Revises: f6ebd146d0dd
Create Date: 2016-06-27 14:12:22.087000

"""

# revision identifiers, used by Alembic.
revision = '5d4117fe39fe'
down_revision = 'f6ebd146d0dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccvote',
    sa.Column('ccvoteID', sa.Integer(), nullable=False),
    sa.Column('voterID', sa.Integer(), nullable=True),
    sa.Column('lmvoteID', sa.Integer(), nullable=True),
    sa.Column('fcvoteID', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fcvoteID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lmvoteID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['voterID'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('ccvoteID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccvote')
    ### end Alembic commands ###
