"""empty message

Revision ID: 66503b938c08
Revises: 913428ec59ed
Create Date: 2016-04-08 23:37:32.304000

"""

# revision identifiers, used by Alembic.
revision = '66503b938c08'
down_revision = '913428ec59ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'login_token',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.add_column('characters', sa.Column('login_token', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'login_token')
    op.alter_column('accounts', 'login_token',
               existing_type=sa.String(length=16),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    ### end Alembic commands ###
