"""empty message

Revision ID: 67b88f2530bb
Revises: c44e71e3e1b6
Create Date: 2017-02-20 16:32:19.153215

"""

# revision identifiers, used by Alembic.
revision = '67b88f2530bb'
down_revision = 'c44e71e3e1b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('alertText', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'alertText')
    # ### end Alembic commands ###
