"""empty message

Revision ID: 7b75d315ee36
Revises: 4c4a14a4d869
Create Date: 2016-04-27 14:31:10.549000

"""

# revision identifiers, used by Alembic.
revision = '7b75d315ee36'
down_revision = '4c4a14a4d869'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('disabled', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ##
    op.drop_column('accounts', 'disabled')
    ### end Alembic commands ###
