"""empty message

Revision ID: 8113af5e2643
Revises: 81ff73bf2f86
Create Date: 2016-05-11 21:01:46.096000

"""

# revision identifiers, used by Alembic.
revision = '8113af5e2643'
down_revision = '81ff73bf2f86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('teamspeak_poke', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'teamspeak_poke')
    ### end Alembic commands ###
