"""empty message

Revision ID: 81ff73bf2f86
Revises: db3c76f99dea
Create Date: 2016-05-11 19:34:46.848000

"""

# revision identifiers, used by Alembic.
revision = '81ff73bf2f86'
down_revision = 'db3c76f99dea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcs',
    sa.Column('accountID', sa.Integer(), nullable=True),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['groupID'], ['waitlist_groups.groupID'], ondelete='CASCADE')
    )
    op.create_table('fleetmanager',
    sa.Column('accountID', sa.Integer(), nullable=True),
    sa.Column('groupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['groupID'], ['waitlist_groups.groupID'], ondelete='CASCADE')
    )
    op.drop_constraint(u'waitlist_groups_ibfk_8', 'waitlist_groups', type_='foreignkey')
    op.drop_constraint(u'waitlist_groups_ibfk_9', 'waitlist_groups', type_='foreignkey')
    op.drop_column(u'waitlist_groups', 'fcID')
    op.drop_column(u'waitlist_groups', 'managerID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'waitlist_groups', sa.Column('managerID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column(u'waitlist_groups', sa.Column('fcID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'waitlist_groups_ibfk_9', 'waitlist_groups', 'characters', ['fcID'], ['id'])
    op.create_foreign_key(u'waitlist_groups_ibfk_8', 'waitlist_groups', 'accounts', ['managerID'], ['id'])
    op.drop_table('fleetmanager')
    op.drop_table('fcs')
    ### end Alembic commands ###
