"""empty message

Revision ID: 871a8dd84cf7
Revises: 44045584e815
Create Date: 2016-03-10 08:10:38.426000

"""

# revision identifiers, used by Alembic.
revision = '871a8dd84cf7'
down_revision = '44045584e815'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invtypes', 'capacity')
    op.drop_column('invtypes', 'raceID')
    op.drop_column('invtypes', 'iconID')
    op.drop_column('invtypes', 'published')
    op.drop_column('invtypes', 'volume')
    op.drop_column('invtypes', 'soundID')
    op.drop_column('invtypes', 'mass')
    op.drop_column('invtypes', 'basePrice')
    op.drop_column('invtypes', 'portionSize')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invtypes', sa.Column('portionSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('invtypes', sa.Column('basePrice', mysql.DECIMAL(precision=19, scale=4), nullable=True))
    op.add_column('invtypes', sa.Column('mass', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('invtypes', sa.Column('soundID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('invtypes', sa.Column('volume', mysql.DOUBLE(asdecimal=True), nullable=True))
    op.add_column('invtypes', sa.Column('published', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True))
    op.add_column('invtypes', sa.Column('iconID', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('invtypes', sa.Column('raceID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('invtypes', sa.Column('capacity', mysql.DOUBLE(asdecimal=True), nullable=True))
    ### end Alembic commands ###
