"""empty message

Revision ID: 877d1e12cd90
Revises: dee6801e4a87
Create Date: 2016-05-06 01:46:35.850000

"""

# revision identifiers, used by Alembic.
revision = '877d1e12cd90'
down_revision = 'dee6801e4a87'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crest_fleets', 'compID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crest_fleets', 'compID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
