"""empty message

Revision ID: 8ec8c7bb9459
Revises: 9ab201421111
Create Date: 2018-09-10 17:52:00.595675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec8c7bb9459'
down_revision = '9ab201421111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogma_effect',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('effect_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.Boolean(name='is_default'), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['invtypes.type_id'], name=op.f('fk_dogma_effect_type_id_invtypes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'effect_id', name=op.f('pk_dogma_effect'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogma_effect')
    # ### end Alembic commands ###
