"""empty message

Revision ID: 8f6e88746b77
Revises: cf588e0dfd5c
Create Date: 2017-01-14 02:15:20.627000

"""

# revision identifiers, used by Alembic.
revision = '8f6e88746b77'
down_revision = 'cf588e0dfd5c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fit_module',
    sa.Column('fitID', sa.Integer(), nullable=False),
    sa.Column('moduleID', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fitID'], ['fittings.id'], ),
    sa.ForeignKeyConstraint(['moduleID'], ['invtypes.typeID'], ),
    sa.PrimaryKeyConstraint('fitID', 'moduleID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fit_module')
    ### end Alembic commands ###
