"""empty message

Revision ID: 9ab201421111
Revises: c2b7b284ed6f
Create Date: 2018-09-08 13:40:35.106054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab201421111'
down_revision = 'c2b7b284ed6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_fit_module_fit_id_fittings'), 'fit_module', type_='foreignkey')
    op.drop_constraint(op.f('fk_fit_module_module_id_invtypes'), 'fit_module', type_='foreignkey')
    op.drop_constraint(op.f('pk_fit_module'), 'fit_module', type_='primary')
    op.add_column('fit_module', sa.Column('location_flag', sa.Integer(), nullable=False, server_default=sa.text('1000')))

    # remove auto increment from invtypes table
    # drop all remaining foreign keys towards the invtypes.type_id column
    op.drop_constraint(op.f('fk_fittings_ship_type_invtypes'), 'fittings', type_='foreignkey')
    # now we can fix the id column (remove the auto increment)
    op.alter_column('invtypes', 'type_id', autoincrement=False, existing_type=sa.Integer, existing_nullable=False)
    op.create_foreign_key(op.f('fk_fittings_ship_type_invtypes'), 'fittings', 'invtypes', ['ship_type'], ['type_id'], onupdate='CASCADE')
    # done removing autoincrement from invtypes table

    # readd keys we removed to change the primary key of fit_module
    op.create_primary_key(op.f('pk_fit_module'), 'fit_module',
                          ['fit_id', 'module_id', 'location_flag'])
    op.create_foreign_key(op.f('fk_fit_module_fit_id_fittings'), 'fit_module', 'fittings', ['fit_id'], ['id'])
    op.create_foreign_key(op.f('fk_fit_module_module_id_invtypes'), 'fit_module', 'invtypes', ['module_id'], ['type_id'], onupdate='CASCADE')

    op.create_table('invcategory',
    sa.Column('category_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('published', sa.Boolean(name='is_published'), nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_invcategory'))
    )
    op.create_table('dogma_attributes',
    sa.Column('type_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['invtypes.type_id'], name=op.f('fk_dogma_attributes_type_id_invtypes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('type_id', 'attribute_id', name=op.f('pk_dogma_attributes'))
    )
    op.create_table('invgroup',
    sa.Column('group_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('published', sa.Boolean(name='is_published'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['invcategory.category_id'], name=op.f('fk_invgroup_category_id_invcategory'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_invgroup'))
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # we don't need to reverse the removal of the autoincrement since it is better for older versions too
    op.drop_constraint(op.f('fk_fit_module_fit_id_fittings'), 'fit_module', type_='foreignkey')
    op.drop_constraint(op.f('fk_fit_module_module_id_invtypes'), 'fit_module', type_='foreignkey')
    op.drop_constraint(op.f('pk_fit_module'), 'fit_module', type_='primary')

    op.drop_column('fit_module', 'location_flag')

    op.create_primary_key(op.f('pk_fit_module'), 'fit_module',
                          ['fit_id', 'module_id'])
    op.create_foreign_key(op.f('fk_fit_module_fit_id_fittings'), 'fit_module', 'fittings', ['fit_id'], ['id'])
    op.create_foreign_key(op.f('fk_fit_module_module_id_invtypes'), 'fit_module', 'invtypes', ['module_id'], ['type_id'])

    op.drop_table('invgroup')
    op.drop_table('dogma_attributes')
    op.drop_table('invcategory')
    # ### end Alembic commands ###
