"""empty message

Revision ID: 9ad747adbff1
Revises: 09414b495bb5
Create Date: 2017-01-25 18:37:58.718000

"""

# revision identifiers, used by Alembic.
revision = '9ad747adbff1'
down_revision = '09414b495bb5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eveapiscope',
    sa.Column('scopeID', sa.Integer(), nullable=False),
    sa.Column('scopeName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('scopeID')
    )
    op.create_index(op.f('ix_eveapiscope_scopeName'), 'eveapiscope', ['scopeName'], unique=False)
    op.create_table('ssotoken',
    sa.Column('accountID', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accountID'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('accountID')
    )
    op.create_table('tokenscope',
    sa.Column('tokenID', sa.Integer(), nullable=False),
    sa.Column('scopeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scopeID'], ['eveapiscope.scopeID'], ),
    sa.ForeignKeyConstraint(['tokenID'], ['ssotoken.accountID'], ),
    sa.PrimaryKeyConstraint('tokenID', 'scopeID')
    )
    #op.create_index(op.f('ix_account_notes_time'), 'account_notes', ['time'], unique=False)
    op.drop_index('ix_role_history_time', table_name='account_notes')
    op.drop_column(u'accounts', 'access_token')
    op.drop_column(u'accounts', 'access_token_expires')
    op.drop_column(u'accounts', 'refresh_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'accounts', sa.Column('refresh_token', mysql.VARCHAR(length=128), nullable=True))
    op.add_column(u'accounts', sa.Column('access_token_expires', mysql.DATETIME(), nullable=True))
    op.add_column(u'accounts', sa.Column('access_token', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_role_history_time', 'account_notes', ['time'], unique=False)
    op.drop_index(op.f('ix_account_notes_time'), table_name='account_notes')
    op.drop_table('tokenscope')
    op.drop_table('ssotoken')
    op.drop_index(op.f('ix_eveapiscope_scopeName'), table_name='eveapiscope')
    op.drop_table('eveapiscope')
    ### end Alembic commands ###
