"""empty message

Revision ID: 9c3d75ef22cb
Revises: d90da500c84c
Create Date: 2016-04-14 20:07:05.478000

"""

# revision identifiers, used by Alembic.
revision = '9c3d75ef22cb'
down_revision = 'd90da500c84c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlists', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('name', table_name='waitlists')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'waitlists', ['name'], unique=True)
    op.alter_column('waitlists', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    ### end Alembic commands ###
