"""empty message

Revision ID: ae9bdeb3e292
Revises: f363cde2b713
Create Date: 2019-07-12 17:05:44.201439

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import func

# revision identifiers, used by Alembic.
revision = 'ae9bdeb3e292'
down_revision = 'f363cde2b713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ssotoken', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ssotoken', 'access_token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    op.create_table('fleet_time',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_fleet_time_character_id_characters'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_fleet_time'))
    )
    op.create_table('fleet_time_by_hull',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('hull_type', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_fleet_time_by_hull_character_id_characters'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hull_type'], ['invtypes.type_id'], name=op.f('fk_fleet_time_by_hull_hull_type_invtypes'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'hull_type', name=op.f('pk_fleet_time_by_hull'))
    )
    op.create_table('fleet_time_last_tracked',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('fleet_time_last_tracked', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_fleet_time_last_tracked_character_id_characters'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk_fleet_time_last_tracked'))
    )
    op.add_column('crest_fleets', sa.Column('registration_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crest_fleets', 'registration_time')
    op.drop_table('fleet_time_last_tracked')
    op.drop_table('fleet_time_by_hull')
    op.drop_table('fleet_time')

    connection = op.get_bind()
    t_tokens = sa.Table(
        'ssotoken',
        sa.MetaData(),
        sa.Column('access_token', sa.Text()),
        sa.Column('access_token_expires', sa.DateTime(), default=datetime.utcnow),
        sa.Column('refresh_token', sa.Text()),
    )

    connection.execute(
        t_tokens.delete()\
            .where(func.length(t_tokens.c.refresh_token) > 128)\
    )
    op.alter_column('ssotoken', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    connection.execute(
        t_tokens.update()\
            .where(func.length(t_tokens.c.access_token) > 128)\
            .values(access_token=None, access_token_expires=datetime.utcnow())\
    )
    op.alter_column('ssotoken', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
