"""empty message

Revision ID: ae9bdeb3e292
Revises: f363cde2b713
Create Date: 2019-07-12 17:05:44.201439

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import func

# revision identifiers, used by Alembic.
revision = 'ae9bdeb3e292'
down_revision = 'f363cde2b713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ssotoken', 'refresh_token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ssotoken', 'access_token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    t_tokens = sa.Table(
        'ssotoken',
        sa.MetaData(),
        sa.Column('access_token', sa.Text()),
        sa.Column('access_token_expires', sa.DateTime(), default=datetime.utcnow),
        sa.Column('refresh_token', sa.Text()),
    )

    connection.execute(
        t_tokens.delete()\
            .where(func.length(t_tokens.c.refresh_token) > 128)\
    )
    op.alter_column('ssotoken', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    connection.execute(
        t_tokens.update()\
            .where(func.length(t_tokens.c.access_token) > 128)\
            .values(access_token=None, access_token_expires=datetime.utcnow())\
    )
    op.alter_column('ssotoken', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
