"""empty message

Revision ID: b0ade35cf837
Revises: e52f17b1d758
Create Date: 2016-03-11 21:21:04.397000

"""

# revision identifiers, used by Alembic.
revision = 'b0ade35cf837'
down_revision = 'e52f17b1d758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incursion_layout',
    sa.Column('constellation', sa.Integer(), nullable=False),
    sa.Column('staging', sa.Integer(), nullable=True),
    sa.Column('headquarter', sa.Integer(), nullable=True),
    sa.Column('dockup', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constellation'], ['constellation.constellationID'], ),
    sa.ForeignKeyConstraint(['dockup'], ['station.stationID'], ),
    sa.ForeignKeyConstraint(['headquarter'], ['solarsystem.solarSystemID'], ),
    sa.ForeignKeyConstraint(['staging'], ['solarsystem.solarSystemID'], ),
    sa.PrimaryKeyConstraint('constellation')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incursion_layout')
    ### end Alembic commands ###
