"""empty message

Revision ID: b4a6bbfeef64
Revises: a92a35286d58
Create Date: 2016-04-16 13:16:15.240000

"""

# revision identifiers, used by Alembic.
revision = 'b4a6bbfeef64'
down_revision = 'a92a35286d58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlists', sa.Column('displayTitle', sa.String(length=100), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlists', 'displayTitle')
    ### end Alembic commands ###
