"""empty message

Revision ID: bae9e3c7f432
Revises: fc929c12e829
Create Date: 2016-03-22 23:20:44.208000

"""

# revision identifiers, used by Alembic.
revision = 'bae9e3c7f432'
down_revision = 'fc929c12e829'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invmarketgroups',
    sa.Column('marketGroupID', sa.Integer(), nullable=False),
    sa.Column('parentGroupID', sa.Integer(), nullable=True),
    sa.Column('marketGroupName', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.Column('iconID', sa.Integer(), nullable=True),
    sa.Column('hasTypes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parentGroupID'], ['invmarketgroups.marketGroupID'], ),
    sa.PrimaryKeyConstraint('marketGroupID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invmarketgroups')
    ### end Alembic commands ###
