"""empty message

Revision ID: c2b7b284ed6f
Revises: 217e6df96f88
Create Date: 2018-06-20 14:04:04.014198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b7b284ed6f'
down_revision = '217e6df96f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('characters', sa.Column('language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_column('characters', 'language')
    op.drop_column('accounts', 'language')
    # ### end Alembic commands ###
