"""empty message

Revision ID: c44e71e3e1b6
Revises: 36abd98c57e5
Create Date: 2017-02-17 15:43:56.453660

"""

# revision identifiers, used by Alembic.
revision = 'c44e71e3e1b6'
down_revision = '36abd98c57e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia',
    sa.Column('triviaID', sa.Integer(), nullable=False),
    sa.Column('createdByID', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('fromTime', sa.DateTime(), nullable=True),
    sa.Column('toTime', sa.DateTime(), nullable=True),
    sa.CheckConstraint('toTime > fromTime'),
    sa.ForeignKeyConstraint(['createdByID'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('triviaID')
    )
    op.create_table('trivia_question',
    sa.Column('questionID', sa.Integer(), nullable=False),
    sa.Column('triviaID', sa.Integer(), nullable=False),
    sa.Column('questionText', sa.String(length=1000), nullable=True),
    sa.Column('answerType', sa.String(length=255), nullable=True),
    sa.Column('answerConnection', sa.Enum('AND', 'OR', 'NOT', 'NONE'), nullable=True),
    sa.Column('inputPlaceholder', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['triviaID'], ['trivia.triviaID'], ),
    sa.PrimaryKeyConstraint('questionID', 'triviaID')
    )
    op.create_table('trivia_answer',
    sa.Column('answerID', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=False),
    sa.Column('answerText', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['trivia_question.questionID'], ),
    sa.PrimaryKeyConstraint('answerID', 'questionID')
    )
    op.create_table('trivia_submission',
    sa.Column('submissionID', sa.Integer(), nullable=False),
    sa.Column('triviaID', sa.Integer(), nullable=True),
    sa.Column('submittorID', sa.Integer(), nullable=True),
    sa.Column('submittorAccountID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submittorAccountID'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['submittorID'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['triviaID'], ['trivia.triviaID'], ),
    sa.PrimaryKeyConstraint('submissionID')
    )
    op.create_table('trivia_submission_answer',
    sa.Column('submissionID', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=False),
    sa.Column('answerText', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['trivia_question.questionID'], ),
    sa.ForeignKeyConstraint(['submissionID'], ['trivia_submission.submissionID'], ),
    sa.PrimaryKeyConstraint('submissionID', 'questionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trivia_submission_answer')
    op.drop_table('trivia_submission')
    op.drop_table('trivia_question')
    op.drop_table('trivia_answer')
    op.drop_table('trivia')
    # ### end Alembic commands ###
