"""empty message

Revision ID: d464aa706238
Revises: 052e5edbdf5d
Create Date: 2017-01-26 18:46:36.473000

"""

# revision identifiers, used by Alembic.
revision = 'd464aa706238'
down_revision = '052e5edbdf5d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_notes_time'), 'account_notes', ['time'], unique=False)
    op.drop_index('email', table_name='accounts')
    op.drop_column('accounts', 'password')
    op.drop_column('accounts', 'email')
    op.add_column('apicache_characterinfo', sa.Column('characterName', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apicache_characterinfo', 'characterName')
    op.add_column('accounts', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('accounts', sa.Column('password', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('email', 'accounts', ['email'], unique=True)
    op.drop_index(op.f('ix_account_notes_time'), table_name='account_notes')
    ### end Alembic commands ###
