"""empty message

Revision ID: db3c76f99dea
Revises: 61cdca7328a6
Create Date: 2016-05-11 11:47:20.859000

"""

# revision identifiers, used by Alembic.
revision = 'db3c76f99dea'
down_revision = '61cdca7328a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ts_dati',
    sa.Column('teamspeakID', sa.Integer(), nullable=False),
    sa.Column('displayName', sa.String(length=128), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('displayHost', sa.String(length=128), nullable=True),
    sa.Column('displayPort', sa.Integer(), nullable=True),
    sa.Column('queryName', sa.String(length=128), nullable=True),
    sa.Column('queryPassword', sa.String(length=128), nullable=True),
    sa.Column('serverID', sa.Integer(), nullable=True),
    sa.Column('channelID', sa.Integer(), nullable=True),
    sa.Column('clientName', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('teamspeakID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ts_dati')
    op.drop_table('settings')
    ### end Alembic commands ###
