"""empty message

Revision ID: e8143468c7c1
Revises: 11ee20a79069
Create Date: 2016-04-07 22:52:52.476000

"""

# revision identifiers, used by Alembic.
revision = 'e8143468c7c1'
down_revision = '11ee20a79069'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entry_fits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entryID', sa.Integer(), nullable=True),
    sa.Column('fitID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entryID'], ['waitlist_entries.id'], ),
    sa.ForeignKeyConstraint(['fitID'], ['fittings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'fittings_ibfk_2', 'fittings', type_='foreignkey')
    op.drop_column(u'fittings', 'waitlist_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'fittings', sa.Column('waitlist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fittings_ibfk_2', 'fittings', 'waitlist_entries', ['waitlist_id'], ['id'], onupdate=u'CASCADE')
    op.drop_table('waitlist_entry_fits')
    ### end Alembic commands ###
