"""empty message

Revision ID: ea41446517f3
Revises: bae9e3c7f432
Create Date: 2016-03-23 23:43:04.047000

"""

# revision identifiers, used by Alembic.
revision = 'ea41446517f3'
down_revision = 'bae9e3c7f432'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apicache_characteraffiliation_name', table_name='apicache_characteraffiliation')
    op.create_index(op.f('ix_apicache_characteraffiliation_name'), 'apicache_characteraffiliation', ['name'], unique=False)
    op.drop_index('name', table_name='apicache_characterid')
    op.drop_index('ix_apicache_corporationinfo_name', table_name='apicache_corporationinfo')
    op.create_index(op.f('ix_apicache_corporationinfo_name'), 'apicache_corporationinfo', ['name'], unique=False)
    op.drop_index('ix_ban_name', table_name='ban')
    op.create_index(op.f('ix_ban_name'), 'ban', ['name'], unique=False)
    op.drop_index('eve_name', table_name='characters')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('eve_name', 'characters', ['eve_name'], unique=True)
    op.drop_index(op.f('ix_ban_name'), table_name='ban')
    op.create_index('ix_ban_name', 'ban', ['name'], unique=True)
    op.drop_index(op.f('ix_apicache_corporationinfo_name'), table_name='apicache_corporationinfo')
    op.create_index('ix_apicache_corporationinfo_name', 'apicache_corporationinfo', ['name'], unique=True)
    op.create_index('name', 'apicache_characterid', ['name'], unique=True)
    op.drop_index(op.f('ix_apicache_characteraffiliation_name'), table_name='apicache_characteraffiliation')
    op.create_index('ix_apicache_characteraffiliation_name', 'apicache_characteraffiliation', ['name'], unique=True)
    ### end Alembic commands ###
