"""empty message

Revision ID: edc810245f94
Revises: 23de9b7d3697
Create Date: 2018-04-14 11:05:44.509020

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = 'edc810245f94'
down_revision = '23de9b7d3697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # drop all sso tokens
    op.drop_constraint(op.f('fk_tokenscope_token_id_ssotoken'), 'tokenscope', type_='foreignkey')

    op.drop_table('tokenscope')
    op.drop_table('eveapiscope')
    op.drop_table('ssotoken')

    op.add_column('characters', sa.Column('owner_hash', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('session_key', sa.Integer(), nullable=False, server_default='0'))

    op.add_column('accounts', sa.Column('session_key', sa.Integer(), nullable=False, server_default='0'))

    op.create_table('ssotoken',
                    sa.Column('token_id', sa.Integer(), nullable=False),
                    sa.Column('character_id', sa.Integer(), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(length=128), nullable=True),
                    sa.Column('access_token', sa.String(length=128), nullable=True),
                    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'],
                                            name=op.f('fk_ssotoken_account_id_accounts'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['character_id'], ['characters.id'],
                                            name=op.f('fk_ssotoken_character_id_characters'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_ssotoken'))
                    )
    op.create_index(op.f('ix_ssotoken_character_id'), 'ssotoken', ['character_id'], unique=False)
    op.create_index(op.f('ix_ssotoken_account_id'), 'ssotoken', ['account_id'], unique=False)
    op.create_index(op.f('ix_ssotoken_character_id_account_id'), 'ssotoken', ['character_id', 'account_id'])

    op.create_table('eveapiscope',
                    sa.Column('token_id', sa.Integer(), nullable=False),
                    sa.Column('scope_name', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['token_id'], ['ssotoken.token_id'],
                                            name=op.f('fk_eveapiscope_token_id_ssotoken'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('token_id', 'scope_name', name=op.f('pk_eveapiscope'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eveapiscope')
    op.drop_table('ssotoken')

    op.drop_column('characters', 'owner_hash')
    op.drop_column('characters', 'session_key')

    op.drop_column('accounts', 'session_key')

    op.create_table('ssotoken',
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('refresh_token', sa.String(length=128), nullable=True),
                    sa.Column('access_token', sa.String(length=128), nullable=True),
                    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'],
                                            name=op.f('fk_ssotoken_account_id_accounts'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_ssotoken'))
                    )

    op.create_table('eveapiscope',
                    sa.Column('scope_id', sa.Integer(), nullable=False),
                    sa.Column('scope_name', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('scope_id', name=op.f('pk_eveapiscope'))
                    )
    op.create_index(op.f('ix_eveapiscope_scope_name'), 'eveapiscope', ['scope_name'], unique=False)

    op.create_table('tokenscope',
                    sa.Column('token_id', sa.Integer(), nullable=False),
                    sa.Column('scope_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['scope_id'], ['eveapiscope.scope_id'],
                                            name=op.f('fk_tokenscope_scope_id_eveapiscope'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['token_id'], ['ssotoken.account_id'],
                                            name=op.f('fk_tokenscope_token_id_ssotoken'), onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('token_id', 'scope_id', name=op.f('pk_tokenscope'))
                    )

    # ### end Alembic commands ###
