"""empty message

Revision ID: f3b1988db9b9
Revises: e8143468c7c1
Create Date: 2016-04-07 22:58:01.752000

"""

# revision identifiers, used by Alembic.
revision = 'f3b1988db9b9'
down_revision = 'e8143468c7c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'waitlist_entry_fits_ibfk_1', 'waitlist_entry_fits', type_='foreignkey')
    op.drop_constraint(u'waitlist_entry_fits_ibfk_2', 'waitlist_entry_fits', type_='foreignkey')
    op.create_foreign_key(None, 'waitlist_entry_fits', 'waitlist_entries', ['entryID'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'waitlist_entry_fits', 'fittings', ['fitID'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist_entry_fits', type_='foreignkey')
    op.drop_constraint(None, 'waitlist_entry_fits', type_='foreignkey')
    op.create_foreign_key(u'waitlist_entry_fits_ibfk_2', 'waitlist_entry_fits', 'fittings', ['fitID'], ['id'])
    op.create_foreign_key(u'waitlist_entry_fits_ibfk_1', 'waitlist_entry_fits', 'waitlist_entries', ['entryID'], ['id'])
    ### end Alembic commands ###
