"""empty message

Revision ID: fc929c12e829
Revises: b0ade35cf837
Create Date: 2016-03-17 15:49:13.442000

"""

# revision identifiers, used by Alembic.
revision = 'fc929c12e829'
down_revision = 'b0ade35cf837'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ban', sa.Column('admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ban', 'characters', ['admin'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ban', type_='foreignkey')
    op.drop_column('ban', 'admin')
    ### end Alembic commands ###
