"""empty message

Revision ID: ffdd6dd99166
Revises: 66503b938c08
Create Date: 2016-04-11 17:44:22.238000

"""

# revision identifiers, used by Alembic.
revision = 'ffdd6dd99166'
down_revision = '66503b938c08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comp_history', sa.Column('exref', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comp_history', 'exref')
    ### end Alembic commands ###
