TYPE_HUMAN = "human"
TYPE_GOT_ACCOUNT_MAIL = "got_account_mail"
TYPE_SENT_ACCOUNT_MAIL = "sent_mail"
TYPE_ROLE_CREATED = "role_created"
TYPE_ACCOUNT_ROLES_CHANGED = "account_roles_changed"
TYPE_ACCOUNT_CREATED = "account_created"
TYPE_ACCOUNT_ACTIVE_CHANGED = "account_active_changed"
TYPE_ACCOUNT_NAME_CHANGED = "account_name_changed"
